### ISSUE TITLE
大佬，求个联系方式交流~

### ISSUE THREAD

**Issue by lingyue328** [A-SOUL-JH/live-statements#1]

**Comment by lingyue328** [comment]
Traceback (most recent call last):
  File "gen.py", line 55, in <module>
    fig.paint()
  File "C:\Users\lingyue\Documents\live-statements-master\figure.py", line 408, in paint
    self.word_cloud()
  File "C:\Users\lingyue\Documents\live-statements-master\figure.py", line 65, in word_cloud
    ).generate_from_frequencies(dict(score))
  File "C:\Python36\lib\site-packages\wordcloud\wordcloud.py", line 404, in generate_from_frequencies
    "got %d." % len(frequencies))
ValueError: We need at least 1 word to plot a word cloud, got 0.


请问这个问题如何解决

**Comment by A-SOUL-JH** [comment]
> Traceback (most recent call last):
> File "gen.py", line 55, in
> fig.paint()
> File "C:\Users\lingyue\Documents\live-statements-master\figure.py", line 408, in paint
> self.word_cloud()
> File "C:\Users\lingyue\Documents\live-statements-master\figure.py", line 65, in word_cloud
> ).generate_from_frequencies(dict(score))
> File "C:\Python36\lib\site-packages\wordcloud\wordcloud.py", line 404, in generate_from_frequencies
> "got %d." % len(frequencies))
> ValueError: We need at least 1 word to plot a word cloud, got 0.
> 
> 请问这个问题如何解决

抱歉，最近有大大大大事，不能及时回复。
gen.py目前是在程序出问题没有正常生成统计图表的时候用于手工生成的统计图表的脚本，不是入口程序。
这个问题应该是因为直接运行gen.py，但是数据库里没有对应房间和时间的弹幕数据。
而且这项目其实还没做完，你非得要用的话，先把settings.py里的LISTEN_ROOMS改成你要统计的直播间id，MEDAL_ASOUL改成对应的粉丝牌，然后运行LiveMonitor.py
